#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_list:
  path: /users
  methods: [GET]
  controller: App\Controller\UserController::index

user_create:
  path: /users
  methods: [POST]
  controller: App\Controller\UserController::create

user_show:
  path: /users/{id}
  methods: [GET]
  controller: App\Controller\UserController::show
  requirements:
    user_id: '\d+'

user_update:
  path: /users/{id}
  methods: [PUT, PATCH]
  controller: App\Controller\UserController::update
  requirements:
    user_id: '\d+'

user_delete:
  path: /users/{id}
  methods: [DELETE]
  controller: App\Controller\UserController::delete
  requirements:
    user_id: '\d+'

movie_list:
  path: /movies
  methods: [GET]
  controller: App\Controller\MovieController::index

movie_create:
  path: /movies
  methods: [POST]
  controller: App\Controller\MovieController::create

movie_show:
  path: /movies/{id}
  methods: [GET]
  controller: App\Controller\MovieController::show
  requirements:
    user_id: '\d+'

movie_update:
  path: /movies/{id}
  methods: [PUT, PATCH]
  controller: App\Controller\MovieController::update
  requirements:
    user_id: '\d+'

movie_delete:
  path: /movies/{id}
  methods: [DELETE]
  controller: App\Controller\MovieController::delete
  requirements:
    user_id: '\d+'
