#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_list:
  path: /users
  methods: [GET]
  controller: App\Controller\UserController::index

user_create:
  path: /users
  methods: [POST]
  controller: App\Controller\UserController::create

user_show:
  path: /users/{uuid}
  methods: [GET]
  controller: App\Controller\UserController::show

user_update:
  path: /users/{uuid}
  methods: [PUT, PATCH]
  controller: App\Controller\UserController::update

user_delete:
  path: /users/{uuid}
  methods: [DELETE]
  controller: App\Controller\UserController::delete

movie_list:
  path: /movies
  methods: [GET]
  controller: App\Controller\MovieController::index

movie_create:
  path: /movies
  methods: [POST]
  controller: App\Controller\MovieController::create

movie_show:
  path: /movies/{uuid}
  methods: [GET]
  controller: App\Controller\MovieController::show

movie_update:
  path: /movies/{uuid}
  methods: [PUT, PATCH]
  controller: App\Controller\MovieController::update

movie_delete:
  path: /movies/{uuid}
  methods: [DELETE]
  controller: App\Controller\MovieController::delete
